import {Component, OnInit} from '@angular/core';
import {Router} from '@angular/router';
import {SecurityService} from '../services/security.service';

@Component({
	selector: 'home-page',
	templateUrl: '/templates/home.html'
})
export class HomePage implements OnInit {
	constructor(
		private router: Router,
		private securityService: SecurityService
	) {};
	
	ngOnInit() {
		if (this.securityService.loginNeeded()) {
			this.router.navigate(['/login']);
			return;
		}
		if (!this.securityService.getEndUser()) {
			this.securityService.currentEndUser()
				.then(response => this.route())
				.catch(error => console.log(error));
		} else {
			this.route();
		}
	};

	route(): void {
		// default page should be users if using autogenerated default user (no contact user)
		if (!this.securityService.getEndUser().contact__r__pg_id__c) {
			this.router.navigate(['/users']);
		// default page should be the current timesheet if you are a contributor
		} else if (this.securityService.getUserIsContributor()) {
			this.router.navigate(['/timesheet']);
		// next check should be whether or not you are approver. If so, send to approval page
		} else if (this.securityService.getUserIsApprover()) {
			this.router.navigate(['/approval']);
		// final default page check should be if you are an admin
		} else if (this.securityService.getUserIsAdmin()) {
			this.router.navigate(['/projects']);
		// otherwise, user has no privileges, and should be redirected to a page informing them to contact an admin
		} else {
			this.router.navigate(['/no-privileges']);
		}
	};
};
